### ISSUE TITLE
Use secure source of randomness

### ISSUE THREAD

**Issue by fabianishere** [wollemat/samurai#20]
I see you are currently using `rand` as source of randomness. However, the quality of `rand` is not guaranteed.

See https://wiki.sei.cmu.edu/confluence/display/c/MSC30-C.+Do+not+use+the+rand%28%29+function+for+generating+pseudorandom+numbers

On *NIX, you could use something like [arc4random](https://man.openbsd.org/arc4random).

**Comment by wollemat** [comment]
Thank you very much for the feedback. I was already looking for a more secure source of randomness. This is very helpful and I will certainly look into it.
